// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Foundation;
using Quiz.PCL;
using Quiz.PCL.Interfaces;
using Quiz.PCL.Models;
using Quiz.PCL.Repository;
using UIKit;

namespace Quiz
{
	public partial class IntroQuizViewController : UIViewController
	{
		public IntroQuizViewController(IntPtr handle) : base(handle)
		{
		}

		public async override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var source = new SmartQuizTableSource(await GetQuizInfo());
			source.NavigationController = this.NavigationController;
			QuizTableView.Source = source;
			QuizTableView.ReloadData();
			QuizTableView.TableFooterView = new UIView();
		}

		private async Task<List<SmartQuiz>> GetQuizInfo()
		{
			IQuizRepository quizRepository = new QuizRepository();
			var data = await quizRepository.GetQuizDetails();
			return (List<SmartQuiz>)data;
		}
	}

	public class SmartQuizTableSource : UITableViewSource
	{

		List<SmartQuiz> TableItems;
		string CellIdentifier = "TableCell";
		public UINavigationController NavigationController;

		public SmartQuizTableSource(List<SmartQuiz> items)
		{
			TableItems = items;
		}

		public override nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
		{
			return 60;
		}

		public override nint RowsInSection(UITableView tableview, nint section)
		{
			return TableItems.Count;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell = tableView.DequeueReusableCell(CellIdentifier);
			SmartQuiz item = TableItems[indexPath.Row];

			//---- if there are no cells to reuse, create a new one
			if (cell == null) { cell = new UITableViewCell(UITableViewCellStyle.Subtitle, CellIdentifier); }

			cell.TextLabel.Text = item.Name;
			cell.DetailTextLabel.Text = item.Description;

			return cell;
		}
		
		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			var studentJoinViewController = UIStoryboard.FromName("Main",null).InstantiateViewController("StudentJoinViewController");
			NavigationController.PushViewController(studentJoinViewController, true);
		}
	}
}
