// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Quiz
{
	public partial class NavigationController : UINavigationController
	{
		public NavigationController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			this.NavigationBar.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
			this.NavigationBar.ShadowImage = new UIImage();
			this.NavigationBar.TintColor = UIColor.White;

			this.NavigationBar.TitleTextAttributes = new UIStringAttributes() {
				ForegroundColor = UIColor.White
			};
		}
	}
}
