// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Quiz
{
	public partial class ParticipantTableViewCell : UITableViewCell
	{
		public ParticipantTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
