// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Quiz
{
	public partial class ParticipantsTableViewCell : UITableViewCell
	{
		public ParticipantsTableViewCell(IntPtr handle) : base(handle)
		{
		}

		public SmartStudent Model { get; set; }

		public static readonly UINib Nib = UINib.FromName("ParticipantsTableViewCell", NSBundle.MainBundle);
		public static readonly NSString Key = new NSString("ParticipantsTableViewCell");

		public static ParticipantsTableViewCell Create()
		{
			return (ParticipantsTableViewCell)Nib.Instantiate(null, null)[0];
		}

		public override void LayoutSubviews()
		{
			base.LayoutSubviews();

			this.LblStudentName.Text = Model.StudentName;
			this.LblStudentSchool.Text = Model.SchoolName;
			this.StudentImage.Image = Model.StudentImage.ToImage();
		}
	}
}
