// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Timers;
using Foundation;
using UIKit;

namespace Quiz
{
	public partial class QuizViewController : UIViewController
	{
		public QuizViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewWillAppear(bool animated)
		{
			StartTimer();
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			UpdateDateTime();
		}

		private void UpdateDateTime()
		{
			var dateTime = DateTime.Now;
			LblTimeRemaining.Text = dateTime.ToString("mm:ss");
		}

		private void StartTimer()
		{
			var timer = new Timer(1000);
			timer.Elapsed += (s, a) => InvokeOnMainThread(UpdateDateTime);
			timer.Start();
		}

	}
}
