// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Quiz
{
	public partial class StudentJoinViewController : UIViewController
	{
		public StudentJoinViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
