// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Quiz
{
	public partial class StudentCollectionViewController : UICollectionViewController
	{
		static NSString studentCellId = new NSString("CollectionCell");
		List<Student> students;

		public StudentCollectionViewController(IntPtr handle) : base(handle)
		{
			var db = Constants.GetConnectionObject();
			var studentData = db.Query<Student>("select * from Student");
			students = new List<Student>();
			foreach (var item in studentData) {
				students.Add(new Student() { StudentName = item.StudentName, StudentImage = item.StudentImage });
			}
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.Title = "Students";
			this.View.BackgroundColor = UIColor.White;
			CollectionView.Frame = new CGRect(60, 70, this.View.Frame.Width - 120, CollectionView.Frame.Height);
			CollectionView.RegisterClassForCell(typeof(CollectionCell), studentCellId);
		}

		public override nint NumberOfSections(UICollectionView collectionView)
		{
			return 1;
		}

		public override nint GetItemsCount(UICollectionView collectionView, nint section)
		{
			return students.Count;
		}

		public override UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
		{
			var studentCell = (CollectionCell)collectionView.DequeueReusableCell(studentCellId, indexPath);
			var student = students[indexPath.Row];
			studentCell.Image = UIImage.FromBundle(student.StudentImage);
			studentCell.TitleLabel = student.StudentName;
			return studentCell;
		}

		public override void ItemHighlighted(UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = collectionView.CellForItem(indexPath);
			cell.ContentView.BackgroundColor = UIColor.Yellow;
		}

		public override void ItemUnhighlighted(UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = collectionView.CellForItem(indexPath);
			cell.ContentView.BackgroundColor = UIColor.White;
		}

		public override bool ShouldHighlightItem(UICollectionView collectionView, NSIndexPath indexPath)
		{
			return true;
		}
	}

	public class CollectionCell : UICollectionViewCell
	{
		UIImageView imageView;
		UILabel titleLabel;
		
		[Export("initWithFrame:")]
		public CollectionCell(CGRect frame) : base(frame)
		{
			ContentView.Layer.BorderColor = UIColor.LightGray.CGColor;
			ContentView.Layer.BorderWidth = 1.0f;
			ContentView.BackgroundColor = UIColor.White;
			ContentView.Frame = new CGRect(0, 0, 200, 200);

			imageView = new UIImageView();
			imageView.Frame = new CGRect(0, 0, 200, 200);

			titleLabel = new UILabel();
			titleLabel.Frame = new CGRect(0, imageView.Frame.Height + 5, 200, 30);
			titleLabel.TextAlignment = UITextAlignment.Center;
			titleLabel.TextColor = UIColor.Black;
			
			ContentView.AddSubview(titleLabel);
			ContentView.AddSubview(imageView);
		}

		public UIImage Image {
			set {
				imageView.Image = value;
			}
		}
		
		public string TitleLabel { 
			set {
				titleLabel.Text = value;
			}
		} 
	} 
}
